POST  http://localhost:3000/add-task-attribute
Content-Type: application/json

{
  "token": "123",
  "taskSid": "WT4f73cf81fd7afb0dc7b7335a6bb32e02",
  "attributeKey": "summary",
  "attributeValue": "Some other summary here"
}

###
POST http://localhost:3000/get-timeline
Content-Type: application/json

{
  "customer": "+49123456789",
  "token": "123"
}

###
POST http://localhost:3000/add-timeline-entry
Content-Type: application/json

{
  "customer": "+49000123123",
  "channel": "whatsapp",
  "summary": "Some summary 3",
  "token": "123"
}

###

POST http://localhost:3000/get-summary
Content-Type: application/json

{
  "customerName": "whatsapp:+4917697868644",
  "conversationSid": "CH8053f897c58f4fd2be46ce188dbbf5bb",
  "token": "123"
}

###

